gallerySourceCode_edition1/grailsGallery/grails-app/controllers/BioController.groovy
class BioController {

    def appBio = {

    }


    def contact = {
        String destinationAddress = grailsApplication.config.contactMail;
        Person person = new Person(params)
        String comment = params.comment
        String messageContent = getMailMessage(person, session['selectedArt'], comment)
        if (person) {
            //todo: send email using person details

           try {
                sendMail {
                  to destinationAddress
                  subject "Someone interested in your artwork"
                  body messageContent
                }

                // send mail to end-user
                 sendMail {
                  to "${person.emailAddress}"
                  subject "Thank you for your interest in Barbara Israel's artwork"
                  body "Thank you for your interest in Barbara Israel's artwork. We will get back to you shortly regarding your inquiry."
                }
           } catch (Exception e) {
               log.error("Error sending email")
               flash.message = "There was an error sending your email. Please try again."
               render(view: "appBio")
           }

        }
        render (view: "contactSuccess")
    }

    private String getMailMessage(Person person, Set selectedArt, def comment) {
        String message = """
            Someone is interested in your artwork.

            Their contact info is:
                Name: ${person.firstName} ${person.lastName}
                Email Address: ${person.emailAddress}
                Phone: ${person.telephone}

            They are interested in the following artwork:

                """

         String selectedArtString = selectedArt.inject("") {String string, ArtEntity art ->
            string + "Name: ${art.title}/n Description: ${art.description}/n"
         }
        return "${message} ${selectedArtString} Comment: ${comment}"
    }

}

gallerySourceCode_edition1/grailsGallery/grails-app/views/bio/appBio.gsp
<%--
  Created by IntelliJ IDEA.
  User: paul
  Date: Jan 25, 2009
  Time: 2:45:06 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
  <head>
       <meta name="layout" content="app" />

      <title>Barbara Israel's Biography</title></head>
  <body>

   <div id="intgallery">
    <div class="breadcrumb">Bio</div>
    <div class="clear"> </div>
    <div class="biobox">
      <div class="biopicture">place image here</div>
      <p>

      ${bio}

      </p>
      <p><a name="contact"></a><span class="titleofpiece" style="align:left">Contact Barbara:</span><br>
        <br>

        <g:if test="${flash.message}">
            ${flash.message}
        </g:if>

         <g:form action="contact" controller="bio">
             <table>
                <tbody>

                    <tr class="prop">
                        <td valign="top" class="name">
                            <label for="firstname">First Name:</label>
                        </td>
                        <td valign="top" class="value ${hasErrors(bean:person,field:'firstName','errors')}">
                            <input type="text" maxlength="50" id="firstname" name="firstname" value="${fieldValue(bean:person,field:'firstName')}"/>
                        </td>
                    </tr>



                     <tr class="prop">
                        <td valign="top" class="name">
                            <label for="lastname">Last Name:</label>
                        </td>
                        <td valign="top" class="value ${hasErrors(bean:person,field:'lastName','errors')}">
                            <input type="text" maxlength="50" id="lastname" name="lastname" value="${fieldValue(bean:person,field:'lastName')}"/>
                        </td>
                    </tr>

                     <tr class="prop">
                        <td valign="top" class="name">
                            <label for="emailAddress">Email Address:</label>
                        </td>
                        <td valign="top" class="value ${hasErrors(bean:person,field:'emailAddress','errors')}">
                            <input type="text" maxlength="50" id="emailAddress" name="emailAddress" value="${fieldValue(bean:person,field:'emailAddress')}"/>
                        </td>
                    </tr>


                       <tr class="prop">
                        <td valign="top" class="name">
                            <label for="telephone">Telephone:</label>
                        </td>
                        <td valign="top" class="value ${hasErrors(bean:person,field:'telephone','errors')}">
                            <input type="text" maxlength="50" id="telephone" name="telephone" value="${fieldValue(bean:person,field:'telephone')}"/>
                        </td>
                    </tr>


                     <tr class="prop">
                        <td valign="top" class="name">
                            <label for="telephone">Comment:</label>
                        </td>
                        <td valign="top" class="value">
                            <textarea id="comment" name="comment" cols="50" rows="10" value="${comment}">

                                </textarea>
                        </td>
                    </tr>
                        <tr><td><td align="right" style="padding-right: 60px;"><input type="submit" value="Submit"/></td></tr>

                   </table>


                   </table>

                </table>

         </g:form>


		<div class="clear"> &nbsp; </div>
             <a href="${createLink(action: "viewCategoriesMenu", controller: "app")}"><img src="../images/returngallery.gif" width="151" height="19"></a> 
    </div>
  </div>
  <div class="clear"></div>


  </body>
</html>

gallerySourceCode_edition1/grailsGallery/grails-app/views/bio/contactSuccess.gsp
<%--
  Created by IntelliJ IDEA.
  User: paul
  Date: Nov 29, 2008
  Time: 8:27:02 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
  <head><title>Thank you for your interest!</title>
   <meta name="layout" content="app" />

  </head>
  <body>


   <div id="intnavline"></div>
    <div id="intgallery">
      <div class="breadcrumb">Thank you</div>
      <div class="clear">
        <div class="interestedbox">
          <table width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr><td><span class="titleofpiece">Title
                  of Piece</span></tr>
				  <tr>
              <td align="center" valign="top"><img src="images/artwork.jpg"></td>
            </tr>


			<tr>
			  <td align="center">
                <p>&nbsp;  </p>
                <p class="smalltext">
                           Thank you for your inquiry.
                  <br>
                    <a href="${createLink(action: "viewCategoriesMenu", controller: "app")}"><img src="${createLinkTo(dir: "images", file: "returngallery.gif")}" ></a>

                  </span> </p>
				</td>
			</tr>
			</table>
        </div>

      </div>

    </div>
  </div>
  <div class="clear"></div>
</div>


  </body>
</html>